#!/bin/bash

#SBATCH --time=00:02:00
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --cpus-per-task=18
#SBATCH --gpus=1
#SBATCH --mem=120G
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --job-name=SImg_test_job
#SBATCH --output=./dump_%A.out 

module purge
module load 2022
module load Anaconda3/2022.05

source activate single_image_fl

srun python ./make_single_img_dataset.py --targetpath $TMPDIR --num_imgs 10000 --seed 42 --imgpath "./static/single_images/ameyoko.jpg" --threads 18
srun python ./test_file.py --input_dir $TMPDIR

